PLUGIN.name = "Better Voice Library"
PLUGIN.author = "Qemist"
PLUGIN.desc = "Changes the voice library to match the one of the clockwork HL2RP schema."

nut.voice.buffer = {}

-- Combine voices.
nut.voice.Register("combine", "1", "One", "npc/metropolice/vo/one.wav");
nut.voice.Register("combine", "2", "Two", "npc/metropolice/vo/two.wav");
nut.voice.Register("combine", "3", "Three", "npc/metropolice/vo/three.wav");
nut.voice.Register("combine", "4", "Four", "npc/metropolice/vo/four.wav");
nut.voice.Register("combine", "5", "Five", "npc/metropolice/vo/five.wav");
nut.voice.Register("combine", "6", "Six", "npc/metropolice/vo/six.wav");
nut.voice.Register("combine", "7", "Seven", "npc/metropolice/vo/seven.wav");
nut.voice.Register("combine", "8", "Eight", "npc/metropolice/vo/eight.wav");
nut.voice.Register("combine", "9", "Nine", "npc/metropolice/vo/nine.wav");
nut.voice.Register("combine", "10", "Ten", "npc/metropolice/vo/ten.wav");
nut.voice.Register("combine", "10-0", "10-0 10-0 viscerator is hunting!", "npc/metropolice/vo/tenzerovisceratorishunting.wav");
nut.voice.Register("combine", "10-2", "10-2", "npc/metropolice/vo/ten2.wav");
nut.voice.Register("combine", "10-4", "10-4", "npc/metropolice/vo/ten4.wav");
nut.voice.Register("combine", "10-8", "10-8, Standing By", "npc/metropolice/vo/ten8standingby.wav");
nut.voice.Register("combine", "(10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav");
nut.voice.Register("combine", "10-91", "10-91d count is...", "npc/metropolice/vo/ten97dcountis.wav");
nut.voice.Register("combine", "10-97 GOA", "10-97 suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav");
nut.voice.Register("combine", "10-97", "10-97", "npc/metropolice/vo/ten97.wav");
nut.voice.Register("combine", "11-99", "Eleven-Ninty-Nine; Officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav");
nut.voice.Register("combine", "404", "Four-Oh-Four Zone", "npc/metropolice/vo/404zone.wav");
nut.voice.Register("combine", "603", "603 Unlawful entry.", "npc/metropolice/vo/unlawfulentry603.wav");
nut.voice.Register("combine", "Acquiring", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav");
nut.voice.Register("combine", "Administer", "Administer", "npc/metropolice/vo/administer.wav");
nut.voice.Register("combine", "Affirmative", "Affirmative", "npc/metropolice/vo/affirmative.wav");
nut.voice.Register("combine", "Affirmative2", "Affirmative", "npc/metropolice/vo/affirmative2.wav");
nut.voice.Register("combine", "Airwatch", "Dispatch, we need airwatch; subject is Five-Oh-Five!", "npc/metropolice/vo/airwatchsubjectis505.wav");
nut.voice.Register("combine", "All Right", "All right, you can go.", "npc/metropolice/vo/allrightyoucango.wav");
nut.voice.Register("combine", "All Units At Location", "All units at location respond to code 3!", "npc/metropolice/vo/allunitsrespondcode3.wav");
nut.voice.Register("combine", "All Units BOL", "All units BOL we have 34S at...", "npc/metropolice/vo/allunitsbol34sat.wav");
nut.voice.Register("combine", "All Units Close", "All units close on suspect!", "npc/metropolice/vo/allunitscloseonsuspect.wav");
nut.voice.Register("combine", "All Units Code 2", "All units code two.", "npc/metropolice/vo/allunitscode2.wav");
nut.voice.Register("combine", "All Units Maintain", "All units maintain this CP.", "npc/metropolice/vo/allunitsmaintainthiscp.wav");
nut.voice.Register("combine", "All Units Move In", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav");
nut.voice.Register("combine", "All Units Report", "All units report location of suspect.", "npc/metropolice/vo/allunitsreportlocationsuspect.wav");
nut.voice.Register("combine", "Amputate", "Amputate", "npc/metropolice/vo/amputate.wav");
nut.voice.Register("combine", "Anti-Citizen One", "Anti-citizen one.", "npc/combine_soldier/vo/anticitizenone.wav");
nut.voice.Register("combine", "Anti-citizen", "Anti-Citizen!", "npc/metropolice/vo/anticitizen.wav");
nut.voice.Register("combine", "Antiseptic", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav");
nut.voice.Register("combine", "Anyone Pick Up That", "Anyone else pick up that uh, 647e reading?", "npc/metropolice/vo/anyonepickup647e.wav");
nut.voice.Register("combine", "Apex", "Apex.", "npc/combine_soldier/vo/apex.wav");
nut.voice.Register("combine", "Apply", "Apply.", "npc/metropolice/vo/apply.wav");
nut.voice.Register("combine", "Assault Point", "Assault point is secure, advance!", "npc/metropolice/vo/assaultpointsecureadvance.wav");
nut.voice.Register("combine", "At Checkpoint", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav");
nut.voice.Register("combine", "Back Me Up", "Back me up I'm out!", "npc/metropolice/vo/backmeupImout.wav");
nut.voice.Register("combine", "Backup", "Backup.", "npc/metropolice/vo/backup.wav");
nut.voice.Register("combine", "Backup2", "Backup.", "vo/trainyard/ba_backup.wav");
nut.voice.Register("combine", "Bearing", "Bearing.", "npc/combine_soldier/vo/bearing.wav");
nut.voice.Register("combine", "Blade", "Blade.", "npc/combine_soldier/vo/blade.wav");
nut.voice.Register("combine", "Block", "Block!", "npc/metropolice/vo/block.wav");
nut.voice.Register("combine", "Block 31", "Block 31 mace.", "npc/combine_soldier/vo/block31mace.wav");
nut.voice.Register("combine", "Block 64", "Block 64 jet.", "npc/combine_soldier/vo/block64mace.wav");
nut.voice.Register("combine", "Block Is Holding", "Block is holding, cohesive.", "npc/metropolice/vo/blockisholdingcohesive.wav");
nut.voice.Register("combine", "Bodypack", "Bodypack holding!", "npc/combine_soldier/vo/bodypackholding.wav");
nut.voice.Register("combine", "Boomer", "Boomer.", "npc/combine_soldier/vo/boomer.wav");
nut.voice.Register("combine", "Bouncer", "Bouncer bouncer!", "npc/combine_soldier/vo/bouncerbouncer.wav");
nut.voice.Register("combine", "Break His Cover", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav");
nut.voice.Register("combine", "Bugs", "Bugs!", "npc/metropolice/vo/bugs.wav");
nut.voice.Register("combine", "Bugs On The Loose", "We've got bugs on the loose!", "npc/metropolice/vo/bugsontheloose.wav");
nut.voice.Register("combine", "CP BOL", "CP we need airwatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav");
nut.voice.Register("combine", "CP Compromised", "CP is compromised; re-establish!", "npc/metropolice/vo/cpiscompromised.wav");
nut.voice.Register("combine", "CP Establish", "CP we need to establish a perimeter at...", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav");
nut.voice.Register("combine", "CP Overrun", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav");
nut.voice.Register("combine", "CP Request", "CP request all units, location and report in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav");
nut.voice.Register("combine", "Call Hotpoint", "Call hotpoint.", "npc/combine_soldier/vo/callhotpoint.wav");
nut.voice.Register("combine", "Can1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav");
nut.voice.Register("combine", "Can2", "Pick... up... that... can.", "npc/metropolice/vo/pickupthecan2.wav");
nut.voice.Register("combine", "Can3", "I said pick up that can!", "npc/metropolice/vo/pickupthecan3.wav");
nut.voice.Register("combine", "Can4", "Now put it, in the trash can.", "npc/metropolice/vo/putitinthetrash1.wav");
nut.voice.Register("combine", "Can5", "I said put it, in the trash can.", "npc/metropolice/vo/putitinthetrash2.wav");
nut.voice.Register("combine", "Canal", "Canal.", "npc/metropolice/vo/canal.wav");
nut.voice.Register("combine", "Canal Block", "Canal block.", "npc/metropolice/vo/canalblock.wav");
nut.voice.Register("combine", "Catch That Blip", "Catch that blip on the stabilization readout?", "npc/metropolice/vo/catchthatbliponstabilization.wav");
nut.voice.Register("combine", "Cauterize", "Cauterize.", "npc/metropolice/vo/cauterize.wav");
nut.voice.Register("combine", "Check For Miscount", "Check for... miscount.", "npc/metropolice/vo/checkformiscount.wav");
nut.voice.Register("combine", "Citizen", "Citizen.", "npc/metropolice/vo/citizen.wav");
nut.voice.Register("combine", "Citizen Summoned", "Reporting; citizen summoned at Two-Rodger conscription for general public service detail T94 Forward Dash Restriction Two.", "npc/metropolice/vo/citizensummoned.wav");
nut.voice.Register("combine", "Classify", "Classify subject name as DB, this block ready for clean out.", "npc/metropolice/vo/classifyasdbthisblockready.wav");
nut.voice.Register("combine", "Cleaned", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav");
nut.voice.Register("combine", "Cleanup", "Engaged in cleanup.", "npc/combine_soldier/vo/engagedincleanup.wav");
nut.voice.Register("combine", "Clear", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav");
nut.voice.Register("combine", "Clear And Code 100", "Clear and code 100.", "npc/metropolice/vo/clearandcode100.wav");
nut.voice.Register("combine", "Clear No 647", "Clear no 647 no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav");
nut.voice.Register("combine", "Closing", "Closing.", "npc/combine_soldier/vo/closing.wav");
nut.voice.Register("combine", "Code 7", "Code 7.", "npc/metropolice/vo/code7.wav");
nut.voice.Register("combine", "Code 100", "Code 100.", "npc/metropolice/vo/code100.wav");
nut.voice.Register("combine", "Come With Me", "You citizen, come with me!", "vo/trainyard/ba_youcomewith.wav");
nut.voice.Register("combine", "Condemned Zone", "Condemned zone!", "npc/metropolice/vo/condemnedzone.wav");
nut.voice.Register("combine", "Confirm ADW", "Confirmed, and ADW on that suspect 10-0.", "npc/metropolice/vo/confirmadw.wav");
nut.voice.Register("combine", "Confirm Not Sterile", "Confirm sector not sterile.", "npc/combine_soldier/vo/confirmsectornotsterile.wav");
nut.voice.Register("combine", "Confirm Priority One", "Confirm priority one sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav");
nut.voice.Register("combine", "Contact", "Contact.", "npc/combine_soldier/vo/contact.wav");
nut.voice.Register("combine", "Contact 243", "Contact with 243 suspect my 10-20 is...", "npc/metropolice/vo/contactwith243suspect.wav");
nut.voice.Register("combine", "Contact Confirm", "Contact confirm!", "npc/combine_soldier/vo/contactconfim.wav");
nut.voice.Register("combine", "Contact Confirm Prosecuting", "Contact confirm, prosecuting!", "npc/combine_soldier/vo/contactconfirmprosecuting.wav");
nut.voice.Register("combine", "Contact Parasitics", "Call contact; parasitics.", "npc/combine_soldier/vo/callcontactparasitics.wav");
nut.voice.Register("combine", "Contact Priority 2", "We have contact with a priority two.", "npc/metropolice/vo/contactwithpriority2.wav");
nut.voice.Register("combine", "Contact Suspect", "Call contact; suspect target one!", "npc/combine_soldier/vo/callcontacttarget1.wav");
nut.voice.Register("combine", "Contained", "Contained.", "npc/combine_soldier/vo/contained.wav");
nut.voice.Register("combine", "Containment", "Containment proceeding.", "npc/combine_soldier/vo/containmentproceeding.wav");
nut.voice.Register("combine", "Control 100", "Control is 100% this location no sign of that 647E.", "npc/metropolice/vo/control100percent.wav");
nut.voice.Register("combine", "Control Section", "Control section.", "npc/metropolice/vo/controlsection.wav");
nut.voice.Register("combine", "Converging", "Converging.", "npc/metropolice/vo/converging.wav");
nut.voice.Register("combine", "Copy", "Copy.", "npc/metropolice/vo/copy.wav");
nut.voice.Register("combine", "Copy That", "Copy that.", "npc/combine_soldier/vo/copythat.wav");
nut.voice.Register("combine", "Cover", "Cover.", "npc/combine_soldier/vo/cover.wav");
nut.voice.Register("combine", "Cover Me", "Cover me.", "npc/combine_soldier/vo/coverme.wav");
nut.voice.Register("combine", "Cover me", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav");
nut.voice.Register("combine", "Criminal Trespass", "Six-Three, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav");
nut.voice.Register("combine", "DB Count", "DB count is...", "npc/metropolice/vo/dbcount.wav");
nut.voice.Register("combine", "DIS", "DIS, updating APB lightmap.", "npc/metropolice/vo/dispupdatingapb.wav");
nut.voice.Register("combine", "Dagger", "Dagger.", "npc/combine_soldier/vo/dagger.wav");
nut.voice.Register("combine", "Defender", "Defender!", "npc/metropolice/vo/defender.wav");
nut.voice.Register("combine", "Degrees", "Degrees.", "npc/combine_soldier/vo/degrees.wav");
nut.voice.Register("combine", "Delivered", "Delivered.", "npc/combine_soldier/vo/delivered.wav");
nut.voice.Register("combine", "Deserviced Area", "Deserviced area!", "npc/metropolice/vo/deservicedarea.wav");
nut.voice.Register("combine", "Designate", "Designate suspect as...", "npc/metropolice/vo/designatesuspectas.wav");
nut.voice.Register("combine", "Designate", "Designate target as...", "npc/combine_soldier/vo/designatetargetas.wav");
nut.voice.Register("combine", "Destroy", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav");
nut.voice.Register("combine", "Dismounting", "Dismounting Hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav");
nut.voice.Register("combine", "Dispatch 10-78", "Dispatch I need 10-78; officer in trouble!", "npc/metropolice/vo/dispatchIneed10-78.wav");
nut.voice.Register("combine", "Displace", "Displace.", "npc/combine_soldier/vo/displace.wav");
nut.voice.Register("combine", "Disreport", "Disreport, suspect incursion.", "npc/metropolice/vo/dispreportssuspectincursion.wav");
nut.voice.Register("combine", "Distribution", "Distribution block.", "npc/metropolice/vo/distributionblock.wav");
nut.voice.Register("combine", "Document", "Document.", "npc/metropolice/vo/document.wav");
nut.voice.Register("combine", "Don't Move", "Don't move!", "npc/metropolice/vo/dontmove.wav");
nut.voice.Register("combine", "Echo", "Echo.", "npc/combine_soldier/vo/echo.wav");
nut.voice.Register("combine", "Engaging", "Engaging.", "npc/combine_soldier/vo/engaging.wav");
nut.voice.Register("combine", "Establish New CP", "Fallout; establish a new CP!", "npc/metropolice/vo/establishnewcp.wav");
nut.voice.Register("combine", "Examine", "Examine.", "npc/metropolice/vo/examine.wav");
nut.voice.Register("combine", "Expired", "Expired", "npc/metropolice/vo/expired.wav");
nut.voice.Register("combine", "External", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav");
nut.voice.Register("combine", "Field Promoted", "Is field promoted to leader one, holding.", "npc/combine_soldier/vo/isfieldpromoted.wav");
nut.voice.Register("combine", "Final Unit", "Is final team unit, request backup!", "npc/combine_soldier/vo/isfinalteamunitbackup.wav");
nut.voice.Register("combine", "Final Verdict", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav");
nut.voice.Register("combine", "Final Warning", "Final warning.", "npc/metropolice/vo/finalwarning.wav");
nut.voice.Register("combine", "Fire To", "Fire to dislocate that interpose!", "npc/metropolice/vo/firetodislocateinterpose.wav");
nut.voice.Register("combine", "Firing To", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav");
nut.voice.Register("combine", "First Warning", "First warning; move away.", "npc/metropolice/vo/firstwarningmove.wav");
nut.voice.Register("combine", "Fix Sightlines", "Fix sightlines, move in.", "npc/combine_soldier/vo/fixsightlinesmovein.wav");
nut.voice.Register("combine", "Flare", "Flare!", "npc/combine_soldier/vo/flash.wav");
nut.voice.Register("combine", "Flare Down", "Flare down!", "npc/combine_soldier/vo/flaredown.wav");
nut.voice.Register("combine", "Flat Line", "Flat line.", "npc/combine_soldier/vo/flatline.wav");
nut.voice.Register("combine", "Flush", "Flush.", "npc/combine_soldier/vo/flush.wav");
nut.voice.Register("combine", "Free Necrotics", "I've free necrotics.", "npc/metropolice/vo/freenecrotics.wav");
nut.voice.Register("combine", "Free Parasites", "We have free parasites.", "npc/combine_soldier/vo/wehavefreeparasites.wav");
nut.voice.Register("combine", "Freeman", "Freeman.", "npc/metropolice/vo/freeman.wav");
nut.voice.Register("combine", "Full Active", "Full active.", "npc/combine_soldier/vo/fullactive.wav");
nut.voice.Register("combine", "Full Response", "Executing full response.", "npc/combine_soldier/vo/executingfullresponse.wav");
nut.voice.Register("combine", "Get 11-44", "Get that 11-44 inbound we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav");
nut.voice.Register("combine", "Get Down", "Get down!", "npc/metropolice/vo/getdown.wav");
nut.voice.Register("combine", "Get In", "Get in!", "vo/trainyard/ba_getin.wav");
nut.voice.Register("combine", "Get In Here", "Get in here.", "vo/trainyard/ba_inhere01.wav");
nut.voice.Register("combine", "Get Out", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav");
nut.voice.Register("combine", "Ghost", "Ghost.", "npc/combine_soldier/vo/ghost.wav");
nut.voice.Register("combine", "Go On", "Go on.", "vo/trainyard/ba_goon.wav");
nut.voice.Register("combine", "Go Sharp", "Go sharp!", "npc/combine_soldier/vo/gosharp.wav");
nut.voice.Register("combine", "Go Sharp2", "Go sharp! Go Sharp!", "npc/combine_soldier/vo/gosharpgosharp.wav");
nut.voice.Register("combine", "Going To", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav");
nut.voice.Register("combine", "Got A 10-107", "Got a 10-107 here; send airwatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav");
nut.voice.Register("combine", "Got Him Again", "Got him again suspect is 10-20 at...", "npc/metropolice/vo/gothimagainsuspect10-20at.wav");
nut.voice.Register("combine", "Got Him Now", "Affirmative, we got him now.", "npc/combine_soldier/vo/affirmativewegothimnow.wav");
nut.voice.Register("combine", "Got One", "Got one accomplice here.", "npc/metropolice/vo/gotoneaccomplicehere.wav");
nut.voice.Register("combine", "Got Suspect One", "I got suspect one here.", "npc/metropolice/vo/gotsuspect1here.wav");
nut.voice.Register("combine", "Grenade", "Grenade!", "npc/metropolice/vo/grenade.wav");
nut.voice.Register("combine", "Grid", "Grid.", "npc/combine_soldier/vo/grid.wav");
nut.voice.Register("combine", "Haha", "Haha.", "npc/metropolice/vo/chuckle.wav");
nut.voice.Register("combine", "Hammer", "Hammer.", "npc/combine_soldier/vo/hammer.wav");
nut.voice.Register("combine", "Harden", "Harden that position!", "npc/combine_soldier/vo/hardenthatposition.wav");
nut.voice.Register("combine", "Hardpoint Scanning", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav");
nut.voice.Register("combine", "He's Gone", "He's gone; 148!", "npc/metropolice/vo/hesgone148.wav");
nut.voice.Register("combine", "Running", "He's running!", "npc/metropolice/vo/hesrunning.wav");
nut.voice.Register("combine", "Up There", "He's up there.", "npc/metropolice/vo/hesupthere.wav");
nut.voice.Register("combine", "Helix", "Helix.", "npc/combine_soldier/vo/helix.wav");
nut.voice.Register("combine", "Help", "Help!", "npc/metropolice/vo/help.wav");
nut.voice.Register("combine", "Hero", "Hero!", "npc/metropolice/vo/hero.wav");
nut.voice.Register("combine", "Hiding", "Hiding, last seen at range.", "npc/metropolice/vo/hidinglastseenatrange.wav");
nut.voice.Register("combine", "High Priority Region", "High priority region!", "npc/metropolice/vo/highpriorityregion.wav");
nut.voice.Register("combine", "Hold It", "Hold it!", "npc/metropolice/vo/holdit.wav");
nut.voice.Register("combine", "Hold This Position", "Protection Team, hold this position.", "npc/metropolice/vo/holdthisposition.wav");
nut.voice.Register("combine", "Holding In Position", "Stabilization team is holding in position.", "npc/combine_soldier/vo/stabilizationteamholding.wav");
nut.voice.Register("combine", "Holding On", "Holding on 10-14 duty at code 4.", "npc/metropolice/vo/holdingon10-14duty.wav");
nut.voice.Register("combine", "Hold it Right There", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav");
nut.voice.Register("combine", "Hostiles Inbound", "Overwatch reports possible hostiles inbound.", "npc/combine_soldier/vo/overwatchreportspossiblehostiles.wav");
nut.voice.Register("combine", "Hurricane", "Hurricane.", "npc/combine_soldier/vo/hurricane.wav");
nut.voice.Register("combine", "I'm Good", "No I'm good.", "vo/trainyard/ba_noimgood.wav");
nut.voice.Register("combine", "I've got a 408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav");
nut.voice.Register("combine", "I Said Move Along", "I said move along.", "npc/metropolice/vo/Isaidmovealong.wav");
nut.voice.Register("combine", "Ice", "Ice.", "npc/combine_soldier/vo/ice.wav");
nut.voice.Register("combine", "I have 10-30", " I have a 10-30 my 10-20 responding; code 2.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav");
nut.voice.Register("combine", "In Infestation Zone", "We are in an infestation zone.", "npc/combine_soldier/vo/weareinaninfestationzone.wav");
nut.voice.Register("combine", "In Position", "In position!", "npc/metropolice/vo/inposition.wav");
nut.voice.Register("combine", "In Position At Hardpoint", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav");
nut.voice.Register("combine", "In Position One", "In position; one ready!", "npc/metropolice/vo/inpositiononeready.wav");
nut.voice.Register("combine", "Inbound", "Inbound.", "npc/combine_soldier/vo/inbound.wav");
nut.voice.Register("combine", "Industrial", "Industrial zone.", "npc/metropolice/vo/industrialzone.wav");
nut.voice.Register("combine", "Infection", "Infection.", "npc/metropolice/vo/infection.wav");
nut.voice.Register("combine", "Infested Zone", "Infested zone.", "npc/metropolice/vo/infestedzone.wav");
nut.voice.Register("combine", "Inject", "Inject.", "npc/metropolice/vo/inject.wav");
nut.voice.Register("combine", "Innoculate", "Innoculate.", "npc/metropolice/vo/innoculate.wav");
nut.voice.Register("combine", "Intercede", "Intercede.", "npc/metropolice/vo/intercede.wav");
nut.voice.Register("combine", "Intercept", "Go active, intercept.", "npc/combine_soldier/vo/goactiveintercept.wav");
nut.voice.Register("combine", "Interlock", "Interlock.", "npc/metropolice/vo/interlock.wav");
nut.voice.Register("combine", "Investigate", "Investigate.", "npc/metropolice/vo/investigate.wav");
nut.voice.Register("combine", "Investigating", "Investigating 10-103.", "npc/metropolice/vo/investigating10-103.wav");
nut.voice.Register("combine", "Ion", "Ion.", "npc/combine_soldier/vo/ion.wav");
nut.voice.Register("combine", "Is 10-108", "Is 10-108!", "npc/metropolice/vo/is10-108.wav");
nut.voice.Register("combine", "Is 415b", "Is 415b.", "npc/metropolice/vo/is415b.wav");
nut.voice.Register("combine", "Is At Hardpoint", "Is at hardpoint, ready to prosecute.", "npc/metropolice/vo/isathardpointreadytoprosecute.wav");
nut.voice.Register("combine", "Is Closing On Suspect", "Is closing on suspect.", "npc/metropolice/vo/isclosingonsuspect.wav");
nut.voice.Register("combine", "Is Down", "Is down!", "npc/metropolice/vo/isdown.wav");
nut.voice.Register("combine", "Is Go", "Is go.", "npc/metropolice/vo/isgo.wav");
nut.voice.Register("combine", "Is Moving In", "Is moving in.", "npc/metropolice/vo/ismovingin.wav");
nut.voice.Register("combine", "Is Passive", "Is passive.", "npc/metropolice/vo/ispassive.wav");
nut.voice.Register("combine", "Is Ready To Go", "Is ready to go!", "npc/metropolice/vo/isreadytogo.wav");
nut.voice.Register("combine", "Isolate", "Isolate.", "npc/metropolice/vo/isolate.wav");
nut.voice.Register("combine", "Issuing", "Issuing malcompliant citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav");
nut.voice.Register("combine", "Jet", "Jet.", "npc/combine_soldier/vo/jet.wav");
nut.voice.Register("combine", "Judge", "Judge.", "npc/combine_soldier/vo/judge.wav");
nut.voice.Register("combine", "Judgement", "Suspect prepare to receive civil judgement.", "npc/metropolice/vo/prepareforjudgement.wav");
nut.voice.Register("combine", "Jury", "Jury.", "npc/metropolice/vo/jury.wav");
nut.voice.Register("combine", "Keep Moving", "Keep moving.", "npc/metropolice/vo/keepmoving.wav");
nut.voice.Register("combine", "Kilo", "Kilo.", "npc/combine_soldier/vo/kilo.wav");
nut.voice.Register("combine", "King", "King.", "npc/metropolice/vo/king.wav");
nut.voice.Register("combine", "Leader", "Leader.", "npc/combine_soldier/vo/leader.wav");
nut.voice.Register("combine", "Level 3", "Got a level 3 civil privacy violator here.", "npc/metropolice/vo/level3civilprivacyviolator.wav");
nut.voice.Register("combine", "Line", "Line.", "npc/metropolice/vo/line.wav");
nut.voice.Register("combine", "Local CP Team", "Local CP Team report status.", "npc/metropolice/vo/localcptreportstatus.wav");
nut.voice.Register("combine", "Location", "Location.", "npc/metropolice/vo/location.wav");
nut.voice.Register("combine", "Lock", "Lock.", "npc/metropolice/vo/lock.wav");
nut.voice.Register("combine", "Lock Your Position", "All units, lock your position.", "npc/metropolice/vo/lockyourposition.wav");
nut.voice.Register("combine", "Looking For Trouble", "Looking for trouble?", "npc/metropolice/vo/lookingfortrouble.wav");
nut.voice.Register("combine", "Lookout", "Lookout!", "npc/metropolice/vo/lookout.wav");
nut.voice.Register("combine", "Lookout Rouge", "Lookout rogue viscerator!", "npc/metropolice/vo/lookoutrogueviscerator.wav");
nut.voice.Register("combine", "Loose Parasitics", "Loose parasitics.", "npc/metropolice/vo/looseparasitics.wav");
nut.voice.Register("combine", "Lost Contact", "Lost contact.", "npc/combine_soldier/vo/lostcontact.wav");
nut.voice.Register("combine", "Loyalty Check Failure", "Control I have a failure to comply with loyalty check procedures, possible 10-103M.", "npc/metropolice/vo/loyaltycheckfailure.wav");
nut.voice.Register("combine", "Mace", "Mace.", "npc/combine_soldier/vo/mace.wav");
nut.voice.Register("combine", "Malcompliant", "Malcompliant 10-107 my 10-20 preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav");
nut.voice.Register("combine", "Malignant", "Malignant.", "npc/metropolice/vo/malignant.wav");
nut.voice.Register("combine", "Match On APB", "I have a match on APB likeness", "npc/metropolice/vo/matchonapblikeness.wav");
nut.voice.Register("combine", "Meters", "Meters.", "npc/metropolice/vo/meters.wav");
nut.voice.Register("combine", "Minor Hits", "Minor hits continuing prosecution.", "npc/metropolice/vo/minorhitscontinuing.wav");
nut.voice.Register("combine", "Motion Check", "Motion check, all radials.", "npc/combine_soldier/vo/motioncheckallradials.wav");
nut.voice.Register("combine", "Move", "Move.", "npc/metropolice/vo/move.wav");
nut.voice.Register("combine", "I Said Move", "I said move!", "vo/trainyard/ba_move01.wav");
nut.voice.Register("combine", "Move Along", "Move along.", "npc/metropolice/vo/movealong.wav");
nut.voice.Register("combine", "Move Along2", "Move along!", "npc/metropolice/vo/movealong3.wav");
nut.voice.Register("combine", "Move Back", "Move back, right now.", "npc/metropolice/vo/movebackrightnow.wav");
nut.voice.Register("combine", "Move It", "Move it!", "npc/metropolice/vo/moveit.wav");
nut.voice.Register("combine", "Move It2", "Move it.", "npc/metropolice/vo/moveit2.wav");
nut.voice.Register("combine", "Move To Arrest", "All units, move to arrest positions.", "npc/metropolice/vo/movetoarrestpositions.wav");
nut.voice.Register("combine", "Moving To Cover", "Moving to cover.", "npc/metropolice/vo/movingtocover.wav");
nut.voice.Register("combine", "Moving To Hardpoint", "Moving to hardpoint.", "npc/metropolice/vo/movingtohardpoint.wav");
nut.voice.Register("combine", "Moving To Hardpoint2", "Moving to hardpoint!", "npc/metropolice/vo/movingtohardpoint2.wav");
nut.voice.Register("combine", "Necrotics", "Necrotics.", "npc/metropolice/vo/necrotics.wav");
nut.voice.Register("combine", "Necrotics Inbound", "Necrotics inbound.", "npc/combine_soldier/vo/necroticsinbound.wav");
nut.voice.Register("combine", "Need Any Help", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav");
nut.voice.Register("combine", "No Contact", "No contact.", "npc/metropolice/vo/nocontact.wav");
nut.voice.Register("combine", "No Viscon", "No viscon.", "npc/combine_soldier/vo/noviscon.wav");
nut.voice.Register("combine", "No Visual", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav");
nut.voice.Register("combine", "Nomad", "Nomad.", "npc/combine_soldier/vo/nomad.wav");
nut.voice.Register("combine", "Non-Tagged Viromes", "We have non-tagged viromes.", "npc/combine_soldier/vo/wehavenontaggedviromes.wav");
nut.voice.Register("combine", "Non-tagged", "Non-tagged viromeshere.", "npc/metropolice/vo/non-taggedviromeshere.wav");
nut.voice.Register("combine", "Noncitizen", "Noncitizen", "npc/metropolice/vo/noncitizen.wav");
nut.voice.Register("combine", "Nonpatrol Region", "Nonpatrol region.", "npc/metropolice/vo/nonpatrolregion.wav");
nut.voice.Register("combine", "Not Secure", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav");
nut.voice.Register("combine", "Nova", "Nova.", "npc/combine_soldier/vo/nova.wav");
nut.voice.Register("combine", "Now", "Now.", "vo/trainyard/ba_thatbeer01.wav");
nut.voice.Register("combine", "Now Get Out", "Now get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav");
nut.voice.Register("combine", "Officer Down", "Officer down! Request all units code 3 to 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav");
nut.voice.Register("combine", "Officer Down 10-99", "Officer down! I am 10-99 I repeat 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav");
nut.voice.Register("combine", "Officer Needs Assistance", "Officer needs assistance I am 11-99!", "npc/metropolice/vo/officerneedsassistance.wav");
nut.voice.Register("combine", "Officer Needs Help", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav");
nut.voice.Register("combine", "Officer Under Fire", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav");
nut.voice.Register("combine", "On Duty", "Unit is on duty, 10-8.", "npc/metropolice/vo/unitisonduty10-8.wav");
nut.voice.Register("combine", "One Contained", "One contained.", "npc/combine_soldier/vo/onecontained.wav");
nut.voice.Register("combine", "One Down", "One down.", "npc/combine_soldier/vo/onedown.wav");
nut.voice.Register("combine", "Outbreak", "Outbreak.", "npc/metropolice/vo/outbreak.wav");
nut.voice.Register("combine", "Outland Biotic", "We got an Outland biotic in here.", "npc/metropolice/vo/outlandbioticinhere.wav");
nut.voice.Register("combine", "Outland Zone", "Outland zone.", "npc/metropolice/vo/outlandzone.wav");
nut.voice.Register("combine", "Overrun", "Overwatch sector overrun, repeat sector overrun.", "npc/combine_soldier/vo/overwatchsectoroverrun.wav");
nut.voice.Register("combine", "Overwatch", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav");
nut.voice.Register("combine", "PT Go Again", "PT go again.", "npc/metropolice/vo/ptgoagain.wav");
nut.voice.Register("combine", "Pacifying", "Pacifying.", "npc/metropolice/vo/pacifying.wav");
nut.voice.Register("combine", "Patrol", "Patrol!", "npc/metropolice/vo/patrol.wav");
nut.voice.Register("combine", "Payback", "Payback.", "npc/combine_soldier/vo/payback.wav");
nut.voice.Register("combine", "Phantom", "Phantom.", "npc/combine_soldier/vo/phantom.wav");
nut.voice.Register("combine", "Picking Up", "Picking up a noncorplexindy here.", "npc/metropolice/vo/pickingupnoncorplexindy.wav");
nut.voice.Register("combine", "Position To Contain", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav");
nut.voice.Register("combine", "Possible 10-103", "Possible 10-103 alert tag units.", "npc/metropolice/vo/possible10-103alerttagunits.wav");
nut.voice.Register("combine", "Possible 404", "Possible 404 here.", "npc/metropolice/vo/possible404here.wav");
nut.voice.Register("combine", "Possible 647E", "Possible 647E; request airwatch to tag.", "npc/metropolice/vo/possible647erequestairwatch.wav");
nut.voice.Register("combine", "Possible Level 3", "Possible level 3 civil privacy violator here.", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav");
nut.voice.Register("combine", "Prep", "Prep for contact, we're going in.", "npc/combine_soldier/vo/prepforcontact.wav");
nut.voice.Register("combine", "Prep For Contact", "Weapons off safe, prep for contact.", "npc/combine_soldier/vo/weaponsoffsafeprepforcontact.wav");
nut.voice.Register("combine", "Prepare For 10-15", "Prepare for 10-15.", "npc/metropolice/vo/preparefor1015.wav");
nut.voice.Register("combine", "Preparing Judge", "Preparing to judge a 10-107, be adviced.", "npc/metropolice/vo/preparingtojudge10-107.wav");
nut.voice.Register("combine", "Preserve", "Preserve.", "npc/metropolice/vo/preserve.wav");
nut.voice.Register("combine", "Pressure", "Pressure.", "npc/metropolice/vo/pressure.wav");
nut.voice.Register("combine", "Priority One Objective", "Priority one objective.", "npc/combine_soldier/vo/priority1objective.wav");
nut.voice.Register("combine", "Priority Two Anti-Citizen", "Have a priority 2 anti-citizen here.", "npc/metropolice/vo/priority2anticitizenhere.wav");
nut.voice.Register("combine", "Priority Two Escapee", "Priority two escapee.", "npc/combine_soldier/vo/prioritytwoescapee.wav");
nut.voice.Register("combine", "Privacy", "Yeah, I'm gonna need me some privacy for this!", "vo/trainyard/ba_privacy.wav");
nut.voice.Register("combine", "Proceed To Checkpoint", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav");
nut.voice.Register("combine", "Prodection Block", "Prodection block.", "npc/metropolice/vo/productionblock.wav");
nut.voice.Register("combine", "Prosecute", "Prosecute.", "npc/metropolice/vo/prosecute.wav");
nut.voice.Register("combine", "Prosecuting", "Prosecuting.", "npc/combine_soldier/vo/prosecuting.wav");
nut.voice.Register("combine", "Protection Complete", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav");
nut.voice.Register("combine", "Protection Team At Location", "Protection team at location report in.", "npc/metropolice/vo/ptatlocationreport.wav");
nut.voice.Register("combine", "Quick", "Quick!", "npc/metropolice/vo/quick.wav");
nut.voice.Register("combine", "Quicksand", "Quicksand.", "npc/combine_soldier/vo/quicksand.wav");
nut.voice.Register("combine", "Radials Free", "Report all radials free.", "npc/combine_soldier/vo/reportallradialsfree.wav");
nut.voice.Register("combine", "Range", "Range.", "npc/combine_soldier/vo/range.wav");
nut.voice.Register("combine", "Ranger", "Ranger.", "npc/combine_soldier/vo/ranger.wav");
nut.voice.Register("combine", "Razor", "Razor.", "npc/combine_soldier/vo/razor.wav");
nut.voice.Register("combine", "Ready Amputate", "Ready to amputate.", "npc/metropolice/vo/readytoamputate.wav");
nut.voice.Register("combine", "Ready Charges", "Ready charges.", "npc/combine_soldier/vo/readycharges.wav");
nut.voice.Register("combine", "Ready To Judge", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav");
nut.voice.Register("combine", "Ready To Prosecute", "Ready to prosecute.", "npc/metropolice/vo/readytoprosecute.wav");
nut.voice.Register("combine", "Ready To Prosecute2", "Ready to prosecute malcomplient citizen, final warning issued.", "npc/metropolice/vo/readytoprosecutefinalwarning.wav");
nut.voice.Register("combine", "Ready Weapons", "Ready weapons.", "npc/combine_soldier/vo/readyweapons.wav");
nut.voice.Register("combine", "Ready Weapons2", "Ready weapons, possible hostiles inbound.", "npc/combine_soldier/vo/readyweaponshostilesinbound.wav");
nut.voice.Register("combine", "Reaper", "Reaper.", "npc/combine_soldier/vo/reaper.wav");
nut.voice.Register("combine", "Reinforcement", "Overwatch, we request reinforcement.", "npc/combine_soldier/vo/overwatchrequestreinforcement.wav");
nut.voice.Register("combine", "Reinforcement Teams", "Reinforcement teams, code 3!", "npc/metropolice/vo/reinforcementteamscode3.wav");
nut.voice.Register("combine", "Report All Positions", "Report, all positions clear.", "npc/combine_soldier/vo/reportallpositionsclear.wav");
nut.voice.Register("combine", "Report Sighting", "Report sighting of possible accomplices.", "npc/metropolice/vo/reportsightingsaccomplices.wav");
nut.voice.Register("combine", "Report Sightlines", "Stay alert, report sightlines.", "npc/combine_soldier/vo/stayalertreportsightlines.wav");
nut.voice.Register("combine", "Repurposed Area", "Repurposed area!", "npc/metropolice/vo/repurposedarea.wav");
nut.voice.Register("combine", "Request Medical", "Request medical!", "npc/combine_soldier/vo/requestmedical.wav");
nut.voice.Register("combine", "Request Secondary", "Is request secondary viscerator, primary is down.", "npc/metropolice/vo/requestsecondaryviscerator.wav");
nut.voice.Register("combine", "Request Stimdose", "Request stimdose.", "npc/combine_soldier/vo/requeststimdose.wav");
nut.voice.Register("combine", "Residential Block", "Residential block.", "npc/metropolice/vo/residentialblock.wav");
nut.voice.Register("combine", "Responding", "Responding.", "npc/metropolice/vo/responding2.wav");
nut.voice.Register("combine", "Restrict", "Restrict.", "npc/metropolice/vo/restrict.wav");
nut.voice.Register("combine", "Restricted Block", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav");
nut.voice.Register("combine", "Ripcord", "Ripcord.", "npc/combine_soldier/vo/ripcord.wav");
nut.voice.Register("combine", "Ripcord2", "Ripcord ripcord!", "npc/combine_soldier/vo/ripcordripcord.wav");
nut.voice.Register("combine", "Rodger That", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav");
nut.voice.Register("combine", "Roller", "Roller!", "npc/metropolice/vo/roller.wav");
nut.voice.Register("combine", "Sacrifice Code 1", "All units sacrifice code 1, maintain this CP!", "npc/metropolice/vo/sacrificecode1maintaincp.wav");
nut.voice.Register("combine", "Savage", "Savage.", "npc/combine_soldier/vo/savage.wav");
nut.voice.Register("combine", "Scar", "Scar.", "npc/combine_soldier/vo/scar.wav");
nut.voice.Register("combine", "Search", "Search!", "npc/metropolice/vo/search.wav");
nut.voice.Register("combine", "Searching for Suspect", "Searching for suspect, no status.", "npc/metropolice/vo/searchingforsuspect.wav");
nut.voice.Register("combine", "Second Warning", "Second warning given!", "npc/metropolice/vo/secondwarning.wav");
nut.voice.Register("combine", "Sector", "Sector", "npc/metropolice/vo/sector.wav");
nut.voice.Register("combine", "Sector Control", "Stabilization team has sector control.", "npc/combine_soldier/vo/stabilizationteamhassector.wav");
nut.voice.Register("combine", "Secure", "Secure.", "npc/combine_soldier/vo/secure.wav");
nut.voice.Register("combine", "Secure No Viscon", "Sector is secure, no viscon.", "npc/combine_soldier/vo/sectorissecurenovison.wav");
nut.voice.Register("combine", "Sentence Delivered", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav");
nut.voice.Register("combine", "Serve", "Serve.", "npc/metropolice/vo/serve.wav");
nut.voice.Register("combine", "Shadow", "Shadow.", "npc/combine_soldier/vo/shadow.wav");
nut.voice.Register("combine", "Sharp Zone", "Sharp zone!", "npc/combine_soldier/vo/sharpzone.wav");
nut.voice.Register("combine", "Shit", "Shit!", "npc/metropolice/vo/shit.wav");
nut.voice.Register("combine", "Shots Fired", "Shots fired hostile malignants here.", "npc/metropolice/vo/shotsfiredhostilemalignants.wav");
nut.voice.Register("combine", "Skyshield Lost Contact", "Skyshield reports lost contact.", "npc/combine_soldier/vo/skyshieldreportslostcontact.wav");
nut.voice.Register("combine", "Sightline Clear", "Sightline is clear.", "npc/combine_soldier/vo/sightlineisclear.wav");
nut.voice.Register("combine", "Skyshield", "Overwatch request skyshield!", "npc/combine_soldier/vo/overwatchrequestskyshield.wav");
nut.voice.Register("combine", "Slam", "Slam.", "npc/combine_soldier/vo/slam.wav");
nut.voice.Register("combine", "Slash", "Slash.", "npc/combine_soldier/vo/slash.wav");
nut.voice.Register("combine", "Sociocide", "Sociocide.", "npc/metropolice/vo/sociocide.wav");
nut.voice.Register("combine", "Spear", "Spear.", "npc/combine_soldier/vo/spear.wav");
nut.voice.Register("combine", "Stab", "Stab.", "npc/combine_soldier/vo/stab.wav");
nut.voice.Register("combine", "Stabilization", "Stabilization jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav");
nut.voice.Register("combine", "Standing By", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav");
nut.voice.Register("combine", "Star", "Star.", "npc/combine_soldier/vo/star.wav");
nut.voice.Register("combine", "Station Block", "Station block.", "npc/metropolice/vo/stationblock.wav");
nut.voice.Register("combine", "Stay Alert", "Stay alert.", "npc/combine_soldier/vo/stayalert.wav");
nut.voice.Register("combine", "Stemboost", "Overwatch orders 3CC stemboost.", "npc/combine_soldier/vo/ovewatchorders3ccstimboost.wav");
nut.voice.Register("combine", "Sterilize", "Sterilize.", "npc/metropolice/vo/sterilize.wav");
nut.voice.Register("combine", "Stick", "Stick.", "npc/metropolice/vo/stick.wav");
nut.voice.Register("combine", "Still 647E", "Still getting that 647E from local surveillance?", "npc/metropolice/vo/stillgetting647e.wav");
nut.voice.Register("combine", "Storm", "Storm.", "npc/combine_soldier/vo/storm.wav");
nut.voice.Register("combine", "Storm System", "Storm system.", "npc/metropolice/vo/stormsystem.wav");
nut.voice.Register("combine", "Striker", "Striker.", "npc/combine_soldier/vo/striker.wav");
nut.voice.Register("combine", "Subject", "Subject.", "npc/metropolice/vo/subject.wav");
nut.voice.Register("combine", "Subject 505", "Subject is 505.", "npc/metropolice/vo/subject505.wav");
nut.voice.Register("combine", "Sundown", "Sundown.", "npc/combine_soldier/vo/sundown.wav");
nut.voice.Register("combine", "Suppressing", "Suppressing.", "npc/combine_soldier/vo/suppressing.wav");
nut.voice.Register("combine", "Supsect Has Moved", "Supsect has moved now to...", "npc/metropolice/vo/supsecthasmovednowto.wav");
nut.voice.Register("combine", "Suspect 11-6", "Suspect 11-6, my 10-20 is...", "npc/metropolice/vo/suspect11-6my1020is.wav");
nut.voice.Register("combine", "Suspect Bleeding", "Suspect is bleeding from multiple wounds.", "npc/metropolice/vo/suspectisbleeding.wav");
nut.voice.Register("combine", "Suspect Unknown", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav");
nut.voice.Register("combine", "Suspend", "Suspend.", "npc/metropolice/vo/suspend.wav");
nut.voice.Register("combine", "Swarm Outbreak", "Swarm outbreak in sector.", "npc/combine_soldier/vo/swarmoutbreakinsector.wav");
nut.voice.Register("combine", "Sweeper", "Sweeper.", "npc/combine_soldier/vo/sweeper.wav");
nut.voice.Register("combine", "Sweeping", "Sweeping for suspect.", "npc/metropolice/vo/sweepingforsuspect.wav");
nut.voice.Register("combine", "Swift", "Swift.", "npc/combine_soldier/vo/swift.wav");
nut.voice.Register("combine", "Sword", "Sword.", "npc/combine_soldier/vo/sword.wav");
nut.voice.Register("combine", "Tag 10-91d", "Tag 10-91d.", "npc/metropolice/vo/tag10-91d.wav");
nut.voice.Register("combine", "Tag One Bug", "Tag One Bug", "npc/metropolice/vo/.wav");
nut.voice.Register("combine", "Tag One Necrotic", "Tag one necrotic.", "npc/metropolice/vo/tagonenecrotic.wav");
nut.voice.Register("combine", "Tag One Parasitic", "Tag one parasitic.", "npc/metropolice/vo/tagoneparasitic.wav");
nut.voice.Register("combine", "Take Cover", "Take cover!", "npc/metropolice/vo/takecover.wav");
nut.voice.Register("combine", "Tap", "Tap.", "npc/metropolice/vo/tap.wav");
nut.voice.Register("combine", "Target", "Target.", "npc/combine_soldier/vo/target.wav");
nut.voice.Register("combine", "Target Compromised", "Target compromised, move in move in!", "npc/combine_soldier/vo/targetcompromisedmovein.wav");
nut.voice.Register("combine", "Target Contact At", "Target contact at...", "npc/combine_soldier/vo/targetcontactat.wav");
nut.voice.Register("combine", "Target Contained", "Overwatch, target contained.", "npc/combine_soldier/vo/overwatchtargetcontained.wav");
nut.voice.Register("combine", "Target Ineffective", "Target ineffective!", "npc/combine_soldier/vo/targetineffective.wav");
nut.voice.Register("combine", "Target My Radial", "Target my radial.", "npc/combine_soldier/vo/targetmyradial.wav");
nut.voice.Register("combine", "Target One", "Target one.", "npc/combine_soldier/vo/targetone.wav");
nut.voice.Register("combine", "Target One Sterilized", "Overwatch target one sterilized.", "npc/combine_soldier/vo/overwatchtarget1sterilized.wav");
nut.voice.Register("combine", "Team Deployed", "Team is deployed and scanning.", "npc/combine_soldier/vo/teamdeployedandscanning.wav");
nut.voice.Register("combine", "Team In Position", "Team in position, advance!", "npc/metropolice/vo/teaminpositionadvance.wav");
nut.voice.Register("combine", "Team Is Down", "Overwatch team is down, sector is non-control.", "npc/combine_soldier/vo/overwatchteamisdown.wav");
nut.voice.Register("combine", "Terminal", "Terminal restriction zone.", "npc/metropolice/vo/terminalrestrictionzone.wav");
nut.voice.Register("combine", "That's a Grenade", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav");
nut.voice.Register("combine", "There He Goes", "There he goes, he's at...", "npc/metropolice/vo/therehegoeshesat.wav");
nut.voice.Register("combine", "There He Is", "There he is!", "npc/metropolice/vo/thereheis.wav");
nut.voice.Register("combine", "This Is Your Second Warning", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav");
nut.voice.Register("combine", "Traker", "Tracker.", "npc/combine_soldier/vo/tracker.wav");
nut.voice.Register("combine", "Transit Block", "Transit block.", "npc/metropolice/vo/transitblock.wav");
nut.voice.Register("combine", "UPI", "UPI.", "npc/metropolice/vo/upi.wav");
nut.voice.Register("combine", "UTL", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav");
nut.voice.Register("combine", "UTL Suspect", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav");
nut.voice.Register("combine", "Uniform", "Uniform.", "npc/combine_soldier/vo/uniform.wav");
nut.voice.Register("combine", "Union", "Union.", "npc/metropolice/vo/union.wav");
nut.voice.Register("combine", "Unit Closing", "Unit is closing.", "npc/combine_soldier/vo/unitisclosing.wav");
nut.voice.Register("combine", "Unit Inbound", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav");
nut.voice.Register("combine", "Unit Moving In", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav");
nut.voice.Register("combine", "Vacate", "Vacate citizen.", "npc/metropolice/vo/vacatecitizen.wav");
nut.voice.Register("combine", "Vamp", "Vamp.", "npc/combine_soldier/vo/vamp.wav");
nut.voice.Register("combine", "Verdict", "You want a noncompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav");
nut.voice.Register("combine", "Vice", "Vice.", "npc/metropolice/vo/vice.wav");
nut.voice.Register("combine", "Victor", "Victor.", "npc/metropolice/vo/victor.wav");
nut.voice.Register("combine", "Viscerator", "Viscerator deployed.", "npc/metropolice/vo/visceratordeployed.wav");
nut.voice.Register("combine", "Viscerator OC", "Watch it viscerator is OC!", "npc/metropolice/vo/visceratorisoc.wav");
nut.voice.Register("combine", "Viscerator Off Grid", "Viscerator is off grid.", "npc/metropolice/vo/visceratorisoffgrid.wav");
nut.voice.Register("combine", "Viscon", "Viscon.", "npc/combine_soldier/vo/viscon.wav");
nut.voice.Register("combine", "Visual Exogens", "Visual on exogens.", "npc/combine_soldier/vo/visualonexogens.wav");
nut.voice.Register("combine", "Waste River", "Waste river.", "npc/metropolice/vo/wasteriver.wav");
nut.voice.Register("combine", "Watch It", "Watch it.", "npc/metropolice/vo/watchit.wav");
nut.voice.Register("combine", "We Are Sociostable", "We are sociostable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav");
nut.voice.Register("combine", "We Got A DB Here", "We got a DB here cancle that 110-102.", "npc/metropolice/vo/wegotadbherecancel10-102.wav");
nut.voice.Register("combine", "We Have 10-108", "We have a 10-108.", "npc/metropolice/vo/wehavea10-108.wav");
nut.voice.Register("combine", "Winder", "Winder.", "npc/combine_soldier/vo/winder.wav");
nut.voice.Register("combine", "Winder Dispatch", "Overwatch request winder dispatch!", "npc/combine_soldier/vo/overwatchrequestwinder.wav");
nut.voice.Register("combine", "Work Force", "Work force intake.", "npc/metropolice/vo/workforceintake.wav");
nut.voice.Register("combine", "Wrap It Up", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav");
nut.voice.Register("combine", "Xray", "Xray.", "npc/metropolice/vo/xray.wav");
nut.voice.Register("combine", "Yellow", "Yellow!", "npc/metropolice/vo/yellow.wav");
nut.voice.Register("combine", "You Knocked It Over", "You knocked it over, pick it up.", "npc/metropolice/vo/youknockeditover.wav");
nut.voice.Register("combine", "Zero", "Zero.", "npc/metropolice/vo/zero.wav");
nut.voice.Register("combine", "Zone", "Zone.", "npc/metropolice/vo/zone.wav");

-- Dispatch voices.
nut.voice.Register("dispatch", "Anti-Citizen", "Attention ground units. Anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav");
nut.voice.Register("dispatch", "Anti-Civil", "Protection team alert. Evidence of anti-civil activity in this community. Code: ASSEMBLE, PLAN, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav");
nut.voice.Register("dispatch", "Person Interest", "Attention please. Unidentified person of interest confirm your civil status with local protection team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav");
nut.voice.Register("dispatch", "Citizen Inaction", "Citizen reminder. Inaction is conspiracy. Report counter behaviour to a Civil Protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav");
nut.voice.Register("dispatch", "Unrest Structure", "Alert community ground protection units, local unrest structure detected. ASSEMBLE, ADMINISTER, PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav");
nut.voice.Register("dispatch", "Status Evasion", "Attention protection team. Status evasion in progress in this community. RESPOND, ISOLATE, ENQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav");
nut.voice.Register("dispatch", "Lockdown", "Attention all ground protection teams. Judgment waiver now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav");
nut.voice.Register("dispatch", "Rations Deducted", "Attention occupants. Your block is now charged with permissive inactive cohesion. Five ration units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav");
nut.voice.Register("dispatch", "Inspection", "Citizen notice. Priority identification check in progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav");
nut.voice.Register("dispatch", "Inspection 2", "Attention please. All citizens in local residential block, assume your inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav");
nut.voice.Register("dispatch", "Miscount Detected", "Attention resident. Miscount detected in your block. Co-operation with your Civil Protection team permit full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav");
nut.voice.Register("dispatch", "Infection", "Attention resident. This block contains potential civil infection. INFORM, CO-OPERATE, ASSEMBLE.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav");
nut.voice.Register("dispatch", "Relocation", "Citizen notice. Failure to co-operate will result in permanent off-world relocation.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav");
nut.voice.Register("dispatch", "Unrest Code", "Attention community. Unrest procedure code is now in effect. INOCULATE, SHIELD, PACIFY. Code: PRESSURE, SWORD, STERILIZE.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav");
nut.voice.Register("dispatch", "Evasion", "Attention please. Evasion behaviour consistent with mal-compliant defendant. Ground protection team, alert. Code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav");
nut.voice.Register("dispatch", "Individual", "Individual. You are charged with social endangerment, level one. Protection unit, prosecution code: DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav");
nut.voice.Register("dispatch", "Autonomous", "Attention all ground protection teams. Autonomous judgement is now in effect, sentencing is now discretionary. Code: AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav");
nut.voice.Register("dispatch", "Citizenship", "Individual. You are convicted of multi anti-civil violations. Implicit citizenship revoked. Status: MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav");
nut.voice.Register("dispatch", "Malcompliance", "Individual. You are charged with capital malcompliance, anti-citizen status approved.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav");
nut.voice.Register("dispatch", "Exogen", "Overwatch acknowledges critical exogen breach, AirWatch augmentation force dispatched and inbound. Hold for reinforcements.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav");
nut.voice.Register("dispatch", "Failure", "Attention ground units. Mission failure will result in permanent off-world assignment. Code reminder: SACRIFICE, COAGULATE, PLAN.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav");

